=== mufajjul/traceability-enforcement-cloud-framework/common/TraceabilityModel/cProv-v1.3.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--Author: Mufy -->
<xs:schema targetNamespace="http://labs.orange.com/uk/cprov#"
	xmlns:prov="http://www.w3.org/ns/prov#" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cprov="http://labs.orange.com/uk/cprov#" elementFormDefault="qualified"
	attributeFormDefault="unqualified" xmlns:opmx="http://openprovenance.org/model/opmx#"
	xmlns:cprovd="http://labs.orange.com/uk/cprovd#">
	<xs:import namespace="http://www.w3.org/ns/prov#" schemaLocation="prov-07012013.xsd"/>
	<xs:element name="traceabilityDocument" type="cprov:TraceabilityDocument"> </xs:element>
	<xs:group name="instance">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="cprov:cProcess"/>
				<xs:element ref="cprov:cResource"/>
				<xs:element ref="cprov:pResource"/>
				<xs:element ref="cprov:transition"/>
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="relation">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="cprov:hadOwnership"/>
				<xs:element ref="cprov:wasExplicitlyCalledBy"/>
				<xs:element ref="cprov:wasImplicitlyCalledBy"/>
				<xs:element ref="cprov:wasInitiallyCalledBy"/>
				<xs:element ref="cprov:wasRecurrentlyCalledBy"/>
				<xs:element ref="cprov:wasReferenceOf"/>
				<xs:element ref="cprov:wasRepresentationOf"/>
				<xs:element ref="cprov:wasVirtualizedBy"/>
				<xs:element ref="cprov:hadTransitionState_a"/>
				<xs:element ref="cprov:hadTransitionState_b"/>
				<xs:element ref="cprov:hadTransitionState_c"/>
			</xs:choice>
		</xs:sequence>

	</xs:group>
	<xs:complexType name="TraceabilityDocument" mixed="false">
		<xs:complexContent>
			<xs:extension base="prov:Document">
				<xs:sequence>
					<xs:group maxOccurs="unbounded" minOccurs="0" ref="cprov:instance"/>
					<xs:group maxOccurs="unbounded" minOccurs="0" ref="cprov:relation"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="resource" type="cprov:Resource"/>
	<xs:complexType name="Resource">
		<xs:complexContent>
			<xs:extension base="prov:Entity">
				<xs:sequence>
					<xs:element name="resType" type="cprov:resType" maxOccurs="1" minOccurs="0"/>
					<xs:element name="userTrustDegree" type="xs:float" maxOccurs="1" minOccurs="0"/>
					<xs:element name="restrictionType" type="cprov:restriction" minOccurs="0"
						maxOccurs="2"/>
					<xs:element name="des" type="xs:string" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="pResource" type="cprov:pResource"/>
	<xs:complexType name="pResource">
		<xs:complexContent>
			<xs:extension base="cprov:Resource">
				<xs:sequence>
					<xs:element name="originIP" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="MAC" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="host" type="cprov:host"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="cResource" type="cprov:cResource"/>
	<xs:complexType name="cResource">
		<xs:complexContent>
			<xs:extension base="cprov:Resource">
				<xs:sequence>
					<xs:element name="userCloudRef" type="xs:string"/>
					<xs:element name="vResourceRef" type="xs:string"/>
					<xs:element name="pResourceRef" type="xs:string"/>
					<xs:element name="isReplicable" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
					<xs:element name="TTL" type="xs:dateTime" maxOccurs="1" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="cProcess" type="cprov:cProcess"/>
	<xs:complexType name="cProcess">
		<xs:complexContent>
			<xs:extension base="prov:Activity">
				<xs:sequence>
					<xs:element name="userCloudRef" type="xs:string" minOccurs="1"/>
					<xs:element name="vProcessRef" type="xs:string" minOccurs="1"/>
					<xs:element name="pProcessRef" type="xs:string" minOccurs="1"/>
					<xs:element name="des" type="xs:string" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="transition" type="cprov:Transition"/>
	<xs:complexType name="Transition">
		<xs:complexContent>
			<xs:extension base="prov:Entity">
				<xs:sequence>
					<!-- <xs:element name="state" type="xs:QName" maxOccurs="1" minOccurs="1"> 
						</xs:element> -->
					<xs:element name="state" type="xs:QName"/>
					<xs:element name="latitude" type="xs:string" maxOccurs="1" minOccurs="0"/>
					<xs:element name="longitude" type="xs:string" maxOccurs="1" minOccurs="0"/>
					<xs:element name="country" type="xs:QName" maxOccurs="1" minOccurs="0"/>
					<xs:element name="region" type="xs:QName" maxOccurs="1" minOccurs="0"/>
					<xs:element name="event" type="xs:QName"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="wasExplicitlyCalledBy" type="cprov:wasExplicitlyCalledBy"/>
	<xs:complexType name="wasExplicitlyCalledBy">
		<xs:complexContent>
			<xs:extension base="prov:Communication">
				<xs:sequence>
					<xs:element name="explicitType" type="xs:QName" maxOccurs="1" minOccurs="0"/>
					<xs:element name="callComm" type="cprov:comm" maxOccurs="1" minOccurs="0"/>
					<xs:element name="callMedium" type="cprov:host" maxOccurs="1" minOccurs="0"/>
					<xs:element name="callNetwork" type="cprov:network" maxOccurs="1" minOccurs="0"
					/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="wasImplicitlyCalledBy" type="cprov:wasImplicitlyCalledBy"/>
	<xs:complexType name="wasImplicitlyCalledBy">
		<xs:complexContent>
			<xs:extension base="prov:Communication">
				<xs:sequence>
					<xs:element name="implicitType" type="xs:QName" minOccurs="0"/>
					<xs:element name="callComm" type="cprov:comm" maxOccurs="1" minOccurs="0"/>
					<xs:element name="callMedium" type="cprov:host" maxOccurs="1" minOccurs="0"/>
					<xs:element name="callNetwork" type="cprov:network" maxOccurs="1" minOccurs="0"
					/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="wasRecurrentlyCalledBy" type="cprov:wasRecurrentlyCalledBy"/>
	<xs:complexType name="wasRecurrentlyCalledBy">
		<xs:complexContent>
			<xs:extension base="prov:Communication">
				<xs:sequence>
					<xs:element name="recurrType" type="xs:QName"/>
					<xs:element name="timeOut" type="xs:dateTime" maxOccurs="1" minOccurs="0"/>
					<xs:element name="callComm" type="xs:QName" maxOccurs="1" minOccurs="0"/>
					<xs:element name="callMedium" type="cprov:host" maxOccurs="1" minOccurs="0"/>
					<xs:element name="callNetwork" type="cprov:network" maxOccurs="1" minOccurs="0"
					/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="wasRepresentationOf" type="cprov:wasRepresentationOf"> </xs:element>
	<xs:complexType name="wasRepresentationOf">
		<xs:complexContent>
			<xs:extension base="prov:Derivation">
				<xs:sequence>
					<xs:element name="method" type="xs:QName" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="wasReferenceOf" type="cprov:wasReferenceOf"/>
	<xs:complexType name="wasReferenceOf">
		<xs:complexContent>
			<xs:extension base="prov:Derivation">
				<xs:sequence>
					<xs:element name="refType" type="xs:QName"/>
					<xs:element name="method" type="xs:QName" minOccurs="0"/>
					<xs:element name="restrictionType" type="cprov:restriction"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="wasInitiallyCalledBy" type="cprov:wasInitiallyCalledBy"/>
	<xs:complexType name="wasInitiallyCalledBy">
		<xs:complexContent>
			<xs:extension base="prov:Association">
				<xs:sequence>
					<xs:element name="purpose" type="xs:QName" maxOccurs="1" minOccurs="0"/>
					<xs:element name="accessMedium" type="cprov:host" maxOccurs="1" minOccurs="0"/>
					<xs:element name="accessNetwork" type="cprov:network" maxOccurs="1"
						minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="wasVirtualizedBy" type="cprov:wasVirtualizedBy"/>
	<xs:complexType name="wasVirtualizedBy">
		<xs:complexContent>
			<xs:extension base="prov:Generation">
				<xs:sequence>
					<xs:element name="purpose" type="xs:QName" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- TODO - change the type name (spelled wrong ) -->
	<xs:element name="hadOwnership" type="cprov:hadOwnership"/>
	<xs:complexType name="hadOwnership">
		<xs:complexContent>
			<xs:extension base="prov:Attribution">
				<xs:sequence>
					<xs:element name="ownershipType" type="cprov:ownership"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="hadTransitionState_a" type="cprov:hadTransitionState_a"/>
	<xs:element name="hadTransitionState_b" type="cprov:hadTransitionState_b"/>
	<xs:element name="hadTransitionState_c" type="cprov:hadTransitionState_c"/>
	<xs:complexType name="hadTransitionState_a">
		<xs:complexContent>
			<xs:extension base="prov:Derivation">
				<xs:sequence>
					<xs:element name="method" type="xs:QName" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="hadTransitionState_b">
		<xs:complexContent>
			<xs:extension base="prov:Generation">
				<xs:sequence>
					<xs:element name="method" type="xs:QName" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="hadTransitionState_c">
		<xs:complexContent>
			<xs:extension base="prov:Attribution">
				<xs:sequence>
					<xs:element name="method" type="xs:QName" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:attribute name="id" type="xs:QName"/>
	<xs:simpleType name="ownership">
		<xs:restriction base="xs:QName">
			<xs:enumeration value="cprovd:originator"/>
			<xs:enumeration value="cprovd:possession"/>
			<xs:enumeration value="cprovd:affiliation"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="restriction">
		<xs:restriction base="xs:QName">
			<xs:enumeration value="cprovd:confidential"/>
			<xs:enumeration value="cprovd:restricted"/>
			<xs:enumeration value="cprovd:general"/>
			<xs:enumeration value="cprovd:non-modifiable"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="resType">
		<xs:restriction base="xs:QName">
			<xs:enumeration value="cprovd:data"/>
			<xs:enumeration value="cprovd:file"/>
			<xs:enumeration value="cprovd:text"/>
			<xs:enumeration value="cprovd:audio"/>
			<xs:enumeration value="cprovd:video"/>
			<xs:enumeration value="cprovd:image"/>
			<xs:enumeration value="cprovd:binary"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="host">
		<xs:restriction base="xs:QName">
			<xs:enumeration value="cprovd:pc"/>
			<xs:enumeration value="cprovd:mobile"/>
			<xs:enumeration value="cprovd:laptop"/>
			<xs:enumeration value="cprovd:tablet"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="state">
		<xs:restriction base="xs:QName">
			<xs:enumeration value="cprovd:origin"/>
			<xs:enumeration value="cprovd:source"/>
			<xs:enumeration value="cprovd:intermediary"/>
			<xs:enumeration value="cprovd:destination"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="comm">
		<xs:restriction base="xs:QName">
			<xs:enumeration value="cprovd:synchronized"/>
			<xs:enumeration value="cprovd:asynchronized"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="network">
		<xs:restriction base="xs:QName">
			<xs:enumeration value="cprovd:thirdGeneration"/>
			<xs:enumeration value="cprovd:fourthGeneration"/>
			<xs:enumeration value="cprovd:wifi"/>
			<xs:enumeration value="cprovd:modem"/>
			<xs:enumeration value="cprovd:ISDN"/>
			<xs:enumeration value="cprovd:DSL"/>
			<xs:enumeration value="cprovd:satelite"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="purpose">
		<xs:restriction base="xs:QName">
			<xs:enumeration value="cprovd:registration"/>
			<xs:enumeration value="cprovd:administration"/>
			<xs:enumeration value="cprovd:verification"/>
			<xs:enumeration value="cprovd:validation"/>
			<xs:enumeration value="cprovd:operation"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== mufajjul/traceability-enforcement-cloud-framework/server/StorageController/serviceTraceabilityTest.xml
<?xml version="1.0" encoding="UTF-8"?><cprov:traceabilityDocument xmlns:cprov="http://labs.orange.com/uk/cprov#" xmlns:ex="http://www.example.org/" xmlns:prov="http://www.w3.org/ns/prov#" xmlns:r="http://labs.orange.com/uk/r#" xmlns:opmx="http://openprovenance.org/model/opmx#" xmlns:cu="http://www.w3.org/1999/xhtml/datatypes/" xmlns:cprovd="http://labs.orange.com/uk/cprovd#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:confidenshare="http://labs.orange.com/uk/confidenshare#" xsi:schemaLocation="http://labs.orange.com/uk/cprov# file:/Users/mufy/Dropbox/EngD/year3/schema/cProv-inherited/cProv-v1.3.xsd"><prov:agent prov:id="ex:ag003"/><cprov:cResource prov:id="ex:e001"><cprov:resType>cprovd:data</cprov:resType><cprov:userTrustDegree>1</cprov:userTrustDegree><cprov:userCloudRef>http://orangecloud/user@matt/cluster001/image001</cprov:userCloudRef><cprov:vResourceRef>/linux/meetingService/res001</cprov:vResourceRef><cprov:pResourceRef>/Cluster001/126.23.43.45/server001/00-12-00-12-00-1/e001</cprov:pResourceRef><cprov:TTL>2015-10-10T12:00:00-05:00</cprov:TTL></cprov:cResource></cprov:traceabilityDocument>
